version: '3'

networks:
  reverse-proxy:
    external: true
  default:

services:

  nginx:
    build:
      context: nginx
    volumes:
      - ${WORK_DIR}/dist:/var/www/html
    environment:
      - VIRTUAL_HOST=${DOMAIN_FRONTEND}
    networks:
      - reverse-proxy
      - default

  workspace:
    build:
      context: npm
    volumes:
      - ${WORK_DIR}:/home/node/react
      - ${WORK_DIR}:${WORK_DIR}
    environment:
      - NODE_ENV=development
    networks:
      - default
    tty: true